name: publish nuget extension
on:
  workflow_run:
    workflows: ['integration']
    types:
      - completed
jobs:
  publish:
    name: build, pack & publish extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Brazil.Standard.Extensions/Brazil.Standard.Extensions.csproj
          PACKAGE_NAME: Brazil.Standard.Extensions
          VERSION_FILE_PATH: Brazil.Standard.Extensions/Brazil.Standard.Extensions.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
